"""Constants for the unified Chapter-3 environment and scenario profiles."""

from pathlib import Path


CH3_MISSION_V1 = "ch3_mission_v1"
CH3_UNKNOWN_MAP_V1 = "ch3_unknown_map_v1"

MISSION_SCENARIO_PROFILES = (
    "S00_STATIC_CLEAR",
    "S10_MOVING_CLEAR",
    "S01_STATIC_OBSTACLE",
    "S11_MOVING_OBSTACLE",
)
# Backward-compatible name used by the existing mission tools.
SCENARIO_PROFILES = MISSION_SCENARIO_PROFILES

UNKNOWN_MAP_PROFILES = (
    "M00_MOVING_CLEAR",
    "M10_MOVING_UNKNOWN_SINGLE",
    "M20_MOVING_UNKNOWN_MULTI",
    "M90_MOVING_KNOWN_ORACLE",
)
ALL_SCENARIO_PROFILES = MISSION_SCENARIO_PROFILES + UNKNOWN_MAP_PROFILES

SCENARIO_SPLITS = (
    "train",
    "validation",
    "smoke_train",
    "smoke_validation",
)
UNKNOWN_MAP_SPLITS = SCENARIO_SPLITS

TRAIN_GENERATOR_SEED = 71001
VALIDATION_GENERATOR_SEED = 72001
SMOKE_TRAIN_GENERATOR_SEED = 73001
SMOKE_VALIDATION_GENERATOR_SEED = 74001
DEFAULT_TRAIN_SCENARIO_COUNT = 200
DEFAULT_VALIDATION_SCENARIO_COUNT = 50
DEFAULT_SMOKE_SCENARIO_COUNT = 2

UNKNOWN_TRAIN_GENERATOR_SEED = 81001
UNKNOWN_VALIDATION_GENERATOR_SEED = 82001
UNKNOWN_SMOKE_TRAIN_GENERATOR_SEED = 83001
UNKNOWN_SMOKE_VALIDATION_GENERATOR_SEED = 84001
UNKNOWN_DEFAULT_TRAIN_SCENARIO_COUNT = 200
UNKNOWN_DEFAULT_VALIDATION_SCENARIO_COUNT = 50
UNKNOWN_DEFAULT_SMOKE_SCENARIO_COUNT = 2

PROJECT_ROOT = Path(__file__).resolve().parent
CH3_ROOT = PROJECT_ROOT / "data" / "chapter3"
CH3_UNKNOWN_ROOT = PROJECT_ROOT / "data" / "chapter3_unknown_map"
UNKNOWN_MANIFEST_ROOT = CH3_UNKNOWN_ROOT / "manifests"
